# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Windows

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: development
          tag: swift-DEVELOPMENT-SNAPSHOT-2022-10-27-a

      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
